<?php
/**
 *
 * @author ln6265431@163.com
 * @date: 2018/1/29下午8:56
 */
namespace  TopCms\Framework\Mvc\Model;
use Phalcon\Mvc\Model;

/**
 * Class BaseModel
 */
class BaseModel extends Model
{
    public function getStringMessages($filter = null)
    {
        $messages = parent::getMessages($filter); // TODO: Change the autogenerated stub
        $result = [];
        foreach ($messages as $message) {
            $result[] = $message->getMessage();
        }
        return $result;
    }
}