update app_article_file_1 set author=1;
update app_article_file_0 set author=1;
update app_article_file_15 set author=1;
update app_article_content set author=1;
alter table `app_article_content` modify author int not null comment '作者id';
alter table `app_article_file` modify author int not null comment '上传者id';
alter table `app_article_file_0` modify author int not null comment '上传者id';
alter table `app_article_file_1` modify author int not null comment '上传者id';
alter table `app_article_file_2` modify author int not null comment '上传者id';
alter table `app_article_file_3` modify author int not null comment '上传者id';
alter table `app_article_file_4` modify author int not null comment '上传者id';
alter table `app_article_file_5` modify author int not null comment '上传者id';
alter table `app_article_file_6` modify author int not null comment '上传者id';
alter table `app_article_file_7` modify author int not null comment '上传者id';
alter table `app_article_file_8` modify author int not null comment '上传者id';
alter table `app_article_file_9` modify author int not null comment '上传者id';
alter table `app_article_file_10` modify author int not null comment '上传者id';
alter table `app_article_file_11` modify author int not null comment '上传者id';
alter table `app_article_file_12` modify author int not null comment '上传者id';
alter table `app_article_file_13` modify author int not null comment '上传者id';
alter table `app_article_file_14` modify author int not null comment '上传者id';
alter table `app_article_file_15` modify author int not null comment '上传者id';